
BE = {"Belgium":"BE"}
GR = {"Greece":"EL"}
LT = {"Lithuania":"LT"}
PT = {"Portugal":"PT"}
BL = {"Bulgaria":"BG"}
SP = {"Spain":"ES"}
LX = {"Luxembourg":"LU"}
RM = {"Romania":"RO"}
CZ = {"Czech Republic":"CZ"}
FR = {"France":"FR"}
HG = {"Hungary":"HU"}
SL = {"Slovenia":"SI"}
DN = {"Denmark":"DK"}
CR = {"Croatia":"HR"}
ML = {"Malta":"MT"}
SK = {"Slovakia":"SK"}
DE = {"Germany":"DE"}
IT = {"Italy":"IT"}
NH = {"Netherlands":"NL"}
FI = {"Finland":"FI"}